#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

npm install
npm run migrate
pm2 restart /home/{{wixed_user}}/{{wixed_dir}}/server.config.js